### ISSUE TITLE
Add option for just validating CITATION.cff

### ISSUE THREAD

**Issue by sim642** [citation-file-format/cffconvert-github-action#12]
Currently the action validates the `CITATION.cff` file and then desperately wants to compare it to `.zenodo.json`. It would be nice to be able to skip the latter part in case using cff is sufficient for Zenodo usage.

**Comment by jspaaks** [comment]
Hi @sim642 , and thanks for making the issue. I agree the github action could use some work, especially after the updates by Zenodo and our own updates to the CFF schema and cffconvert major version update. I was thinking along the lines of simplifying this github action to the point where it is much closer to cffconvert 2.0's command line interface. Not sure when I will have time to work on this though. 

In the meantime, you could opt for using [cffconvert from Dockerhub](https://hub.docker.com/r/citationcff/cffconvert/tags) using something like:

```yaml

name: cffconvert

on:
  push:
    branches: [ main ]
    
jobs:

  validate:
    name: cffconvert
    runs-on: ubuntu-latest
    steps:    

      - name: Check out repository
        uses: actions/checkout@v2    

      - name: Verify whether CITATION.cff passes validation
        uses: docker://citationcff/cffconvert:2.0.0
        with:
          entrypoint: cffconvert
          args: --validate

```

Hope this helps!

**Comment by jspaaks** [comment]
When making changes, perhaps we can simply release 1.0.0, which will include the zenodo comparison, and then work on 2.0.0 which is a more direct gh action wrapper around cffconvert 2.0.0's cli arguments. Additionally, the cffconvert gh action should work based on the image from dockerhub, to address https://github.com/citation-file-format/cffconvert-github-action/issues/10

**Comment by jspaaks** [comment]
We are making changes at the moment. Once we release 2.0.0 (should be within a couple of days), one should be able to do almost exactly what it said in my snippet above:

```yaml
name: cffconvert

on: push

jobs:
  verify:
    name: "cffconvert"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v2

      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"
```

Other parts of cffconvert's functionality should also be accessible by simply passing other values for `args`, e.g.: 

```yaml
      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--infile ./some/subdir/CITATION.cff --format zenodo"
```

Hope this helps!
