### ISSUE TITLE
Suggest constraining action to run on file change

### ISSUE THREAD

**Issue by abelsiqueira** [citation-file-format/cffconvert-github-action#61]
Add the following (need to test) on the examples.
```
on:
  push:
    paths:
      - 'CITATION.cff'
```
